# Generated by Django 4.2.7 on 2024-02-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discription',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
